periodics:

- name: periodic-testing-retester
  interval: 20m  # Retest at most 1 PR per 20m, which should not DOS the queue.
  agent: kubernetes
  decorate: true
  annotations:
    testgrid-dashboards: jetstack-testing-janitors
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Periodically comments /retest against approved and lgtm'd PRs that are failing
  spec:
    containers:
    - image: gcr.io/k8s-testimages/commenter:v20181130-0587c4793
      args:
      - /app/robots/commenter/commenter-image.binary
      - |-
        --query=is:pr
        -label:do-not-merge
        -label:do-not-merge/blocked-paths
        -label:do-not-merge/cherry-pick-not-approved
        -label:do-not-merge/hold
        -label:do-not-merge/release-note-label-needed
        -label:do-not-merge/work-in-progress
        label:lgtm
        label:approved
        status:failure
        -label:needs-rebase
        -label:needs-ok-to-test
        -label:"cncf-cla: no"
        repo:jetstack/navigator
        repo:jetstack/cert-manager
      - --token=/etc/token/bot-github-token
      - |-
        --comment=/retest
        This bot automatically retries jobs that failed/flaked on approved PRs (send feedback to [jetstack](https://github.com/jetstack)).
        Review the [full test history](https://jetstack-build-infra.appspot.com/pr/{{.Number}}) for this PR.
        Silence the bot with an `/lgtm cancel` comment for consistent failures.
      - --template
      - --ceiling=1
      - --confirm
      - --updated=30m
      volumeMounts:
      - name: token
        mountPath: /etc/token
    volumes:
    - name: token
      secret:
        secretName: retest-bot-token

- name: periodic-testing-close
  interval: 1h
  agent: kubernetes
  decorate: true
  annotations:
    testgrid-dashboards: jetstack-testing-janitors
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Closes PRs and issues that are marked 'rotten' and have been inactive for 30d
  spec:
    containers:
    - image: gcr.io/k8s-testimages/commenter:v20181130-0587c4793
      args:
      - /app/robots/commenter/commenter-image.binary
      - |-
        --query=repo:jetstack/cert-manager
        -label:lifecycle/frozen
        label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/token/bot-github-token
      - |-
        --comment=Rotten issues close after 30d of inactivity.
        Reopen the issue with `/reopen`.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        Send feedback to [jetstack](https://github.com/jetstack).
        /close
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/token
    volumes:
    - name: token
      secret:
        secretName: retest-bot-token

- name: periodic-testing-rotten
  interval: 1h
  agent: kubernetes
  decorate: true
  annotations:
    testgrid-dashboards: jetstack-testing-janitors
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Marks PRs and issues that are marked 'stale' and have been inactive for 30d as 'rotten'
  spec:
    containers:
    - image: gcr.io/k8s-testimages/commenter:v20181130-0587c4793
      args:
      - /app/robots/commenter/commenter-image.binary
      - |-
        --query=repo:jetstack/cert-manager
        -label:lifecycle/frozen
        label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=720h
      - --token=/etc/token/bot-github-token
      - |-
        --comment=Stale issues rot after 30d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle rotten`.
        Rotten issues close after an additional 30d of inactivity.
        If this issue is safe to close now please do so with `/close`.
        Send feedback to [jetstack](https://github.com/jetstack).
        /lifecycle rotten
        /remove-lifecycle stale
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/token
    volumes:
    - name: token
      secret:
        secretName: retest-bot-token

- name: periodic-testing-stale
  interval: 1h
  agent: kubernetes
  decorate: true
  annotations:
    testgrid-dashboards: jetstack-testing-janitors
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Marks PRs and issues that have been inactive for 30d as 'stale'
  spec:
    containers:
    - image: gcr.io/k8s-testimages/commenter:v20181130-0587c4793
      args:
      - /app/robots/commenter/commenter-image.binary
      - |-
        --query=repo:jetstack/cert-manager
        -label:lifecycle/frozen
        -label:lifecycle/stale
        -label:lifecycle/rotten
      - --updated=2160h
      - --token=/etc/token/bot-github-token
      - |-
        --comment=Issues go stale after 90d of inactivity.
        Mark the issue as fresh with `/remove-lifecycle stale`.
        Stale issues rot after an additional 30d of inactivity and eventually close.
        If this issue is safe to close now please do so with `/close`.
        Send feedback to [jetstack](https://github.com/jetstack).
        /lifecycle stale
      - --template
      - --ceiling=10
      - --confirm
      volumeMounts:
      - name: token
        mountPath: /etc/token
    volumes:
    - name: token
      secret:
        secretName: retest-bot-token
