periodics:

- name: ci-cert-manager-next-bazel
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs 'bazel test //...'
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-next-bazel-experimental
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs 'bazel test //...' using the 'experimental' Bazel version
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-experimental
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-next-e2e-v1-16
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.16"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-next-e2e-v1-17
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.17"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-next-e2e-v1-18
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.18 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.18"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-next-e2e-v1-19
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.19 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.19"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-next-e2e-v1-20
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-1.2
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-next
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200428-6b034c1-2.2.0
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.20"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"