periodics:

- name: ci-cert-manager-previous-bazel
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    description: Runs 'bazel test //...'
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-previous-bazel-experimental
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs 'bazel test //...' using the 'experimental' Bazel version
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-experimental
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
      - name: ndots
        value: "1"

# kind based cert-manager e2e job
- name: ci-cert-manager-previous-e2e-v1-11
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.11 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.11"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-previous-e2e-v1-12
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.12 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.12"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"


- name: ci-cert-manager-previous-e2e-v1-13
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.13 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.13"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"


- name: ci-cert-manager-previous-e2e-v1-14
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.14 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.14"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"


- name: ci-cert-manager-previous-e2e-v1-15
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.15 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.15"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"


- name: ci-cert-manager-previous-e2e-v1-16
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.16"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-previous-e2e-v1-17
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.14
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-previous
    testgrid-alert-email: james+alerts@munnelly.eu
    description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200407-37ac701-2.2.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.17"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"
