presubmits:
  jetstack/kube-oidc-proxy:

  - name: pull-kube-oidc-proxy-verify
    always_run: true
    cluster: gke
    context: pull-kube-oidc-proxy-verify
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - make
        - all
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-kube-oidc-proxy-demo
    always_run: true
    cluster: gke
    context: pull-kube-oidc-proxy-demo
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    branches:
    - master
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - make
        - -C
        - ./demo
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-11
    context: pull-kube-oidc-proxy-e2e-v1-11
    always_run: false
    cluster: gke
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.11.10"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-12
    context: pull-kube-oidc-proxy-e2e-v1-12
    always_run: false
    cluster: gke
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.12.10"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-13
    context: pull-kube-oidc-proxy-e2e-v1-13
    always_run: false
    cluster: gke
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.13.10"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-14
    context: pull-kube-oidc-proxy-e2e-v1-14
    always_run: false
    cluster: gke
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.14.10"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-15
    context: pull-kube-oidc-proxy-e2e-v1-15
    always_run: false
    cluster: gke
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.15.7"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-16
    context: pull-kube-oidc-proxy-e2e-v1-16
    always_run: false
    cluster: gke
    optional: false
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.16.4"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-17
    context: pull-kube-oidc-proxy-e2e-v1-17
    always_run: false
    cluster: gke
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.17.2"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-18
    context: pull-kube-oidc-proxy-e2e-v1-18
    always_run: true
    cluster: gke
    optional: false
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210122-46f3dbf-1.13.4
        args:
        - runner
        - make
        - e2e
        env:
        - name: KUBE_OIDC_PROXY_K8S_VERSION
          value: "1.18.0"
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
