presubmits:
  jetstack/kube-oidc-proxy:

  - name: pull-kube-oidc-proxy-verify
    always_run: true
    context: pull-kube-oidc-proxy-verify
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    spec:
      containers:
      - image: golang:1.12.1
        args:
        - make
        - all
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-kube-oidc-proxy-demo
    always_run: true
    context: pull-kube-oidc-proxy-demo
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    spec:
      containers:
      - image: golang:1.12.1
        args:
        - make
        - -C
        - ./demo
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-11
    context: pull-kube-oidc-proxy-e2e-v1-11
    # Match everything except PRs that only touch docs/
    always_run: false
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:v20190320-1080345
        args:
        - hack/docker-start-wrapper.sh
        - make
        - e2e-1.11
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-12
    context: pull-kube-oidc-proxy-e2e-v1-12
    # Match everything except PRs that only touch docs/
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:v20190320-1080345
        args:
        - hack/docker-start-wrapper.sh
        - make
        - e2e-1.12
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-13
    context: pull-kube-oidc-proxy-e2e-v1-13
    # Match everything except PRs that only touch docs/
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:v20190320-1080345
        args:
        - hack/docker-start-wrapper.sh
        - make
        - e2e-1.13
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-14
    context: pull-kube-oidc-proxy-e2e-v1-14
    # Match everything except PRs that only touch docs/
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:v20190320-1080345
        args:
        - hack/docker-start-wrapper.sh
        - make
        - e2e-1.14
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-15
    context: pull-kube-oidc-proxy-e2e-v1-15
    # Match everything except PRs that only touch docs/
    always_run: true
    optional: false
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    decoration_config:
      ssh_key_secrets:
      - jetstack-pulling-bot
    clone_uri: "git@github.com:jetstack/kube-oidc-proxy.git"
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:v20190320-1080345
        args:
        - hack/docker-start-wrapper.sh
        - make
        - e2e-1.15
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
