presets:
- labels:
    preset-cert-manager-publish-bot-credentials: "true"
  env:
  - name: DOCKER_CONFIG
    value: /etc/pusher-docker-config
  volumes:
  - name: pusher-config
    secret:
      secretName: cert-manager-publish-bot
  volumeMounts:
  - name: pusher-config
    mountPath: /etc/pusher-docker-config
    readOnly: true

- labels:
    preset-chart-museum-deploy-credentials: "true"
  env:
  - name: CHART_SERVICE_ACCOUNT
    value: /etc/chart-museum-service-account/service-account.json
  volumes:
  - name: chart-deploy-config
    secret:
      secretName: chart-museum-deploy-key
  volumeMounts:
  - name: chart-deploy-config
    mountPath: /etc/chart-museum-service-account
    readOnly: true

postsubmits:
  jetstack/cert-manager:

  # Publish releases for v0.8.x
  - name: post-cert-manager-release
    cluster: trusted
    branches:
    # Only run this job on v0.8.x tags
    - ^v?0\.8\.\d+(-(alpha|beta)\.\d+)?$
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cert-manager-publish-bot-credentials: "true"
      preset-chart-museum-deploy-credentials: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190409-ad28471-0.24.1
        args:
        # Wrap the release script with the runner so we can use docker-in-docker
        - runner
        - hack/release.sh
        env:
        # Confirm we do want to push the image
        - name: CONFIRM
          value: "yes"
        - name: SKIP_MANIFESTS
          value: "yes"
        resources:
          requests:
            cpu: 1500m
            memory: 3Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # Publish releases for v0.7.x
  - name: post-cert-manager-release-previous
    cluster: trusted
    branches:
    # Only run this job on v0.7.x tags
    - ^v?0\.7\.\d+(-(alpha|beta)\.\d+)?$
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cert-manager-publish-bot-credentials: "true"
      preset-chart-museum-deploy-credentials: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190409-ad28471-0.21.0
        args:
        # Wrap the release script with the runner so we can use docker-in-docker
        - runner
        - hack/release.sh
        env:
        # Confirm we do want to push the image
        - name: CONFIRM
          value: "yes"
        - name: SKIP_MANIFESTS
          value: "yes"
        resources:
          requests:
            cpu: 1500m
            memory: 3Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory

  # Run postsubmit against the master branch
  - name: post-cert-manager-release-canary
    cluster: trusted
    branches:
    - master
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cert-manager-publish-bot-credentials: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190409-ad28471-0.24.1
        args:
        # Wrap the release script with the runner so we can use docker-in-docker
        - runner
        - bazel
        - run
        - //hack/release
        - --
        - --images
        - --app-version=canary
        - --publish
        resources:
          requests:
            cpu: 1500m
            memory: 3Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
