periodics:

- name: ci-cert-manager-bazel
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190408-4d1853d-0.24.1
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi

- name: ci-cert-manager-bazel-experimental
  interval: 12h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190409-72e658d-experimental
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi

# kind based cert-manager e2e job
- name: ci-cert-manager-e2e-v1-11
  interval: 4h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190408-4d1853d-0.24.1
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      # TODO: remove this after https://github.com/jetstack/cert-manager/pull/1215 merges
      - name: KIND_IMAGE
        value: eu.gcr.io/jetstack-build-infra-images/kind:1.11.4-1
      - name: K8S_VERSION
        value: "1.11"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory

- name: ci-cert-manager-e2e-v1-12
  interval: 4h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190408-4d1853d-0.24.1
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      # TODO: remove this after https://github.com/jetstack/cert-manager/pull/1215 merges
      - name: KIND_IMAGE
        value: eu.gcr.io/jetstack-build-infra-images/kind:1.12.2-1
      - name: K8S_VERSION
        value: "1.12"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory

- name: ci-cert-manager-e2e-v1-13
  interval: 4h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20190408-4d1853d-0.24.1
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      # TODO: remove this after https://github.com/jetstack/cert-manager/pull/1215 merges
      - name: KIND_IMAGE
        value: kindest/node:v1.13.2
      - name: K8S_VERSION
        value: "1.13"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
