# job templates

# puppet module verify using ruby tooling
.puppet_module_verify: &puppet_module_verify
  skip_report: false
  max_concurrency: 4
  agent: kubernetes
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/jetstack-build-infra/ruby:2.4.0
      args:
      - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
      - "--root=/workspace"
      - "--upload=gs://jetstack-logs/pr-logs"
      - "--clean"
      env:
      - name: BUNDLE_DIR
        value: /cache/bundle/$(JOB_NAME)
      resources:
        requests:
          cpu: 750m
          memory: 1Gi
      volumeMounts:
      - name: bundle-cache
        mountPath: /cache/bundle
    volumes:
    - name: bundle-cache
      hostPath:
        path: /var/lib/libvirt/caches/bundle
        type: Directory
  trigger: "(?m)^/test( all| verify| quick verify),?(\\s+|$)"
  rerun_command: "/test verify"

# puppet module acceptance tests using ruby tooling, elevated privileges due
# to requirement to run nested VMs
.puppet_module_acceptance: &puppet_module_acceptance
  skip_report: false
  max_concurrency: 2
  agent: kubernetes
  labels:
    preset-service-account: "true"
    libvirt-socket: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    # Note: this is not supported yet by prow PodSpec, taint temporary removed
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: gcr.io/jetstack-build-infra/ruby:2.4.0
      args:
      - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
      - "--root=/workspace"
      - "--upload=gs://jetstack-logs/pr-logs"
      - "--clean"
      env:
      - name: BUNDLE_DIR
        value: /cache/bundle/$(JOB_NAME)
      resources:
        requests:
          cpu: 750m
          memory: 1Gi
      volumeMounts:
      - name: bundle-cache
        mountPath: /cache/bundle
      - name: vagrant-boxes
        mountPath: /root/.vagrant.d/boxes
    volumes:
    - name: bundle-cache
      hostPath:
        path: /var/lib/libvirt/caches/bundle
        type: Directory
    - name: vagrant-boxes
      hostPath:
        path: /var/lib/libvirt/caches/vagrant-boxes
        type: Directory
  trigger: "(?m)^/test( all| acceptance),?(\\s+|$)"
  rerun_command: "/test acceptance"


presubmits:
  jetstack/puppet-module-aws_ebs:
  - <<: *puppet_module_verify
    always_run: true
    name: puppet-module-aws_ebs-quick-verify
    context: puppet-module-aws_ebs-quick-verify

  jetstack/puppet-module-calico:
  - <<: *puppet_module_verify
    always_run: true
    name: puppet-module-calico-quick-verify
    context: puppet-module-calico-quick-verify
  - <<: *puppet_module_acceptance
    name: puppet-module-calico-acceptance
    context: puppet-module-calico-acceptance

  jetstack/puppet-module-etcd:
  - <<: *puppet_module_verify
    always_run: true
    name: puppet-module-etcd-quick-verify
    context: puppet-module-etcd-quick-verify
  - <<: *puppet_module_acceptance
    always_run: true
    name: puppet-module-etcd-acceptance-single-node
    context: puppet-module-etcd-acceptance-single-node
  - <<: *puppet_module_acceptance
    always_run: true
    name: puppet-module-etcd-acceptance-three-node
    context: puppet-module-etcd-acceptance-three-node

  jetstack/puppet-module-kubernetes:
  - <<: *puppet_module_verify
    always_run: true
    name: puppet-module-kubernetes-quick-verify
    context: puppet-module-kubernetes-quick-verify
  - <<: *puppet_module_acceptance
    always_run: true
    name: puppet-module-kubernetes-acceptance
    context: puppet-module-kubernetes-acceptance

  jetstack/puppet-module-kubernetes_addons:
  - <<: *puppet_module_verify
    name: puppet-module-kubernetes_addons-quick-verify
    context: puppet-module-kubernetes_addons-quick-verify
    always_run: true

  jetstack/puppet-module-prometheus:
  - <<: *puppet_module_verify
    name: puppet-module-prometheus-quick-verify
    context: puppet-module-prometheus-quick-verify
    always_run: true

  jetstack/puppet-module-tarmak:
  - <<: *puppet_module_verify
    name: puppet-module-tarmak-quick-verify
    context: puppet-module-tarmak-quick-verify
    always_run: true

  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-11-centos
    context: puppet-module-tarmak-acceptance-1-11-centos
    always_run: false
    trigger: "(?m)^/test( all| acceptance-centos( v?1.11)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.11"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-10-centos
    context: puppet-module-tarmak-acceptance-1-10-centos
    always_run: false
    trigger: "(?m)^/test( all| acceptance-centos( v?1.10)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.10"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-9-centos
    context: puppet-module-tarmak-acceptance-1-9-centos
    always_run: false
    trigger: "(?m)^/test( all| acceptance-centos( v?1.9)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.9"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-8-centos
    context: puppet-module-tarmak-acceptance-1-8-centos
    always_run: true
    trigger: "(?m)^/test( all| acceptance-centos( v?1.8)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.8"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-7-centos
    context: puppet-module-tarmak-acceptance-1-7-centos
    always_run: false
    trigger: "(?m)^/test( all| acceptance-centos( v?1.7)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.7"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-6-centos
    context: puppet-module-tarmak-acceptance-1-6-centos
    always_run: false
    trigger: "(?m)^/test( all| acceptance-centos( v?1.6)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.6"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-5-centos
    context: puppet-module-tarmak-acceptance-1-5-centos
    always_run: false
    trigger: "(?m)^/test( all| acceptance-centos( v?1.5)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos v1.5"
  - <<: *puppet_module_acceptance
    name: puppet-module-tarmak-acceptance-1-10-ubuntu
    context: puppet-module-tarmak-acceptance-1-10-ubuntu
    always_run: false
    trigger: "(?m)^/test( all| acceptance-ubuntu( v?1.10)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-ubuntu v1.10"

  jetstack/puppet-module-vault_client:
  - <<: *puppet_module_verify
    name: puppet-module-vault_client-quick-verify
    context: puppet-module-vault_client-quick-verify
    always_run: true

  - <<: *puppet_module_acceptance
    name: puppet-module-vault_client-acceptance-centos
    context: puppet-module-vault_client-acceptance-centos
    trigger: "(?m)^/test( all| acceptance(-centos)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-centos"
    always_run: true
  - <<: *puppet_module_acceptance
    name: puppet-module-vault_client-acceptance-ubuntu
    context: puppet-module-vault_client-acceptance-ubuntu
    trigger: "(?m)^/test( all| acceptance(-ubuntu)?|)( \\[.+\\])?$"
    rerun_command: "/test acceptance-ubuntu"
    always_run: true

  jetstack/tarmak:
  # puppet module aws_ebs
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-aws_ebs-quick-verify
    context: tarmak-puppet-module-aws_ebs-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/aws_ebs).*$"
    trigger: "(?m)^/test( all| puppet| puppet-aws_ebs| puppet-verify| puppet-aws_ebs-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-aws_ebs-verify"
  # puppet module aws_es_proxy
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-aws_es_proxy-quick-verify
    context: tarmak-puppet-module-aws_es_proxy-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/aws_es_proxy).*$"
    trigger: "(?m)^/test( all| puppet| puppet-aws_es_proxy| puppet-verify| puppet-aws_es_proxy-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-aws_es_proxy-verify"
  # puppet module calico
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-calico-quick-verify
    context: tarmak-puppet-module-calico-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/calico).*$"
    trigger: "(?m)^/test( all| puppet| puppet-calico| puppet-verify| puppet-calico-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-calico-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-calico-acceptance
    context: tarmak-puppet-module-calico-acceptance
    always_run: false
    run_if_changed: "^(puppet/modules/calico).*$"
    trigger: "(?m)^/test( all| puppet| puppet-calico| puppet-calico-acceptance|)( \\[.+\\])?$"
    rerun_command: "/test puppet-calico-acceptance"
  # puppet module etcd
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-etcd-quick-verify
    context: tarmak-puppet-module-etcd-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/etcd).*$"
    trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-verify| puppet-etcd-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-etcd-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-etcd-acceptance-single-node
    context: tarmak-puppet-module-etcd-acceptance-single-node
    always_run: false
    run_if_changed: "^(puppet/modules/etcd).*$"
    trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-etcd-acceptance-single-node|)( \\[.+\\])?$"
    rerun_command: "/test puppet-etcd-acceptance-single-node"
    run_after_success:
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-etcd-acceptance-three-node
      context: tarmak-puppet-module-etcd-acceptance-three-node
      always_run: false
      run_if_changed: "^(puppet/modules/etcd).*$"
      trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-etcd-acceptance-three-node|)( \\[.+\\])?$"
      rerun_command: "/test puppet-etcd-acceptance-three-node"
  # puppet module fluent_bit
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-fluent_bit-quick-verify
    context: tarmak-puppet-module-fluent_bit-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/fluent_bit).*$"
    trigger: "(?m)^/test( all| puppet| puppet-fluent_bit| puppet-verify| puppet-fluent_bit-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-fluent_bit-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-fluent_bit-acceptance
    context: tarmak-puppet-module-fluent_bit-acceptance
    always_run: false
    run_if_changed: "^(puppet/modules/fluent_bit).*$"
    trigger: "(?m)^/test( all| puppet| puppet-fluent_bit| puppet-fluent_bit-acceptance|)( \\[.+\\])?$"
    rerun_command: "/test puppet-fluent_bit-acceptance"
  # puppet module kubernetes
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-kubernetes-quick-verify
    context: tarmak-puppet-module-kubernetes-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/kubernetes).*$"
    trigger: "(?m)^/test( all| puppet| puppet-kubernetes| puppet-verify| puppet-kubernetes-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-kubernetes-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-kubernetes-acceptance
    context: tarmak-puppet-module-kubernetes-acceptance
    always_run: false
    run_if_changed: "^(puppet/modules/kubernetes).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-kubernetes-acceptance|)( \\[.+\\])?$"
    rerun_command: "/test puppet-kubernetes-acceptance"
  # puppet module kubernetes_addons
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-kubernetes_addons-quick-verify
    context: tarmak-puppet-module-kubernetes_addons-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/kubernetes_addons).*$"
    trigger: "(?m)^/test( all| puppet| puppet-kubernetes_addons| puppet-verify| puppet-kubernetes_addons-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-kubernetes_addons-verify"
  # puppet module prometheus
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-prometheus-quick-verify
    context: tarmak-puppet-module-prometheus-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/prometheus).*$"
    trigger: "(?m)^/test( all| puppet| puppet-prometheus| puppet-verify| puppet-prometheus-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-prometheus-verify"
  # puppet module tarmak
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-tarmak-quick-verify
    context: tarmak-puppet-module-tarmak-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-verify| puppet-tarmak-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-10-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-10-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.10)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.10"
    run_after_success:
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-tarmak-acceptance-1-10-ubuntu
      context: tarmak-puppet-module-tarmak-acceptance-1-10-ubuntu
      always_run: false
      run_if_changed: "^(puppet/modules).*$"
      trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-ubuntu( v?1.10)?|)( \\[.+\\])?$"
      rerun_command: "/test puppet-tarmak-acceptance-ubuntu v1.10"
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-tarmak-acceptance-1-11-centos
      context: tarmak-puppet-module-tarmak-acceptance-1-11-centos
      always_run: false
      run_if_changed: "^(puppet/modules).*$"
      trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.11)?|)( \\[.+\\])?$"
      rerun_command: "/test puppet-tarmak-acceptance-centos v1.11"
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-tarmak-acceptance-1-9-centos
      context: tarmak-puppet-module-tarmak-acceptance-1-9-centos
      always_run: false
      run_if_changed: "^(puppet/modules).*$"
      trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.9)?|)( \\[.+\\])?$"
      rerun_command: "/test puppet-tarmak-acceptance-centos v1.9"
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-tarmak-acceptance-1-8-centos
      context: tarmak-puppet-module-tarmak-acceptance-1-8-centos
      always_run: false
      run_if_changed: "^(puppet/modules).*$"
      trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.8)?|)( \\[.+\\])?$"
      rerun_command: "/test puppet-tarmak-acceptance-centos v1.8"
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-tarmak-acceptance-1-7-centos
      context: tarmak-puppet-module-tarmak-acceptance-1-7-centos
      always_run: false
      run_if_changed: "^(puppet/modules).*$"
      trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.7)?|)( \\[.+\\])?$"
      rerun_command: "/test puppet-tarmak-acceptance-centos v1.7"
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-tarmak-acceptance-1-6-centos
      context: tarmak-puppet-module-tarmak-acceptance-1-6-centos
      always_run: false
      run_if_changed: "^(puppet/modules).*$"
      trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.6)?|)( \\[.+\\])?$"
      rerun_command: "/test puppet-tarmak-acceptance-centos v1.6"
  # puppet module vault_client
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-vault_client-quick-verify
    context: tarmak-puppet-module-vault_client-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/vault_client).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_client| puppet-verify| puppet-vault_client-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_client-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-vault_client-acceptance-centos
    context: tarmak-puppet-module-vault_client-acceptance-centos
    always_run: false
    run_if_changed: "^(puppet/modules/vault_client).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_client| puppet-vault_client-acceptance-centos|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_client-acceptance-centos"
    run_after_success:
    - <<: *puppet_module_acceptance
      name: tarmak-puppet-module-vault_client-acceptance-ubuntu
      context: tarmak-puppet-module-vault_client-acceptance-ubuntu
      always_run: false
      run_if_changed: "^(puppet/modules/vault_client).*$"
      trigger: "(?m)^/test( all| puppet| puppet-vault_client| puppet-vault_client-acceptance-ubuntu|)( \\[.+\\])?$"
      rerun_command: "/test puppet-vault_client-acceptance-ubuntu"

  - name: tarmak-quick-verify
    always_run: true
    skip_report: false
    context: tarmak-quick-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/jetstack-build-infra/gcloud-in-go:0.7
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify( quick)?|)( \\[.+\\])?$"
    rerun_command: "/test verify quick"

  - name: tarmak-docs-verify
    always_run: true
    skip_report: false
    context: tarmak-docs-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/jetstack-build-infra/sphinx-docs:0.1
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/workspace"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify( docs)?|)( \\[.+\\])?$"
    rerun_command: "/test verify docs"
