# job templates

# puppet module verify using ruby tooling
.puppet_module_verify: &puppet_module_verify
  skip_report: false
  max_concurrency: 4
  agent: kubernetes
  decorate: true
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/tarmak-ruby:v20180831-4ff2528-2.4.4
      command:
      - /bin/sh
      - -c
      - cd puppet/modules/$(echo ${JOB_NAME} | awk -F- '{print $(NF-2)}') && { if test -e .fixtures.yml.local; then export FIXTURES_YML=.fixtures.yml.local ; fi; } && make verify
      env:
      - name: BUNDLE_DIR
        value: /cache/bundle/$(JOB_NAME)
      resources:
        requests:
          cpu: 750m
          memory: 1Gi
      volumeMounts:
      - name: bundle-cache
        mountPath: /cache/bundle
    volumes:
    - name: bundle-cache
      hostPath:
        path: /var/lib/libvirt/caches/bundle
        type: Directory

# puppet module acceptance tests using ruby tooling, elevated privileges due
# to requirement to run nested vms. (modern decorators)
.puppet_module_acceptance: &puppet_module_acceptance
  skip_report: false
  max_concurrency: 2
  decorate: true
  agent: kubernetes
  labels:
    preset-service-account: "true"
    libvirt-socket: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    # Note: this is not supported yet by prow PodSpec, taint temporary removed
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/tarmak-ruby:v20180831-4ff2528-2.4.4
      command:
      - hack/ci/run-puppet-job.sh
      env:
      - name: BUNDLE_DIR
        value: /cache/bundle/$(JOB_NAME)
      resources:
        requests:
          cpu: 750m
          memory: 1Gi
      volumeMounts:
      - name: bundle-cache
        mountPath: /cache/bundle
      - name: vagrant-boxes
        mountPath: /root/.vagrant.d/boxes
    volumes:
    - name: bundle-cache
      hostPath:
        path: /var/lib/libvirt/caches/bundle
        type: Directory
    - name: vagrant-boxes
      hostPath:
        path: /var/lib/libvirt/caches/vagrant-boxes
        type: Directory

presubmits:
  jetstack/tarmak:
  # puppet role spec
  - <<: *puppet_module_verify
    name: tarmak-puppet-roles-quick-verify
    context: tarmak-puppet-roles-quick-verify
    always_run: false
    run_if_changed: "^(puppet).*$"
    trigger: "(?m)^/test( all| puppet| puppet-roles| puppet-verify| puppet-roles-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-roles-verify"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/tarmak-ruby:v20180831-4ff2528-2.4.4
        command:
        - make
        - -C
        - puppet
        - verify
        env:
        - name: BUNDLE_DIR
          value: /cache/bundle/$(JOB_NAME)
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
        volumeMounts:
        - name: bundle-cache
          mountPath: /cache/bundle
      volumes:
      - name: bundle-cache
        hostPath:
          path: /var/lib/libvirt/caches/bundle
          type: Directory
  # puppet module aws_ebs
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-aws_ebs-quick-verify
    context: tarmak-puppet-module-aws_ebs-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/aws_ebs).*$"
    trigger: "(?m)^/test( all| puppet| puppet-aws_ebs| puppet-verify| puppet-aws_ebs-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-aws_ebs-verify"
  # puppet module aws_es_proxy
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-aws_es_proxy-quick-verify
    context: tarmak-puppet-module-aws_es_proxy-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/aws_es_proxy).*$"
    trigger: "(?m)^/test( all| puppet| puppet-aws_es_proxy| puppet-verify| puppet-aws_es_proxy-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-aws_es_proxy-verify"
  # puppet module calico
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-calico-quick-verify
    context: tarmak-puppet-module-calico-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/calico).*$"
    trigger: "(?m)^/test( all| puppet| puppet-calico| puppet-verify| puppet-calico-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-calico-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-calico-acceptance
    context: tarmak-puppet-module-calico-acceptance
    always_run: false
    run_if_changed: "^(puppet/modules/calico).*$"
    trigger: "(?m)^/test( all| puppet| puppet-calico| puppet-calico-acceptance|)( \\[.+\\])?$"
    rerun_command: "/test puppet-calico-acceptance"
  # puppet module consul
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-consul-quick-verify
    context: tarmak-puppet-module-consul-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/consul).*$"
    trigger: "(?m)^/test( all| puppet| puppet-consul| puppet-verify| puppet-consul-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-consul-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-consul-acceptance-single-node
    context: tarmak-puppet-module-consul-acceptance-single-node
    always_run: false
    run_if_changed: "^(puppet/modules/consul).*$"
    trigger: "(?m)^/test( all| puppet| puppet-consul| puppet-consul-acceptance-single-node|)( \\[.+\\])?$"
    rerun_command: "/test puppet-consul-acceptance-single-node"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-consul-acceptance-three-node
    context: tarmak-puppet-module-consul-acceptance-three-node
    always_run: false
    run_if_changed: "^(puppet/modules/consul).*$"
    trigger: "(?m)^/test( all| puppet| puppet-consul| puppet-consul-acceptance-three-node|)( \\[.+\\])?$"
    rerun_command: "/test puppet-consul-acceptance-three-node"
  # puppet module etcd
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-etcd-quick-verify
    context: tarmak-puppet-module-etcd-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/etcd).*$"
    trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-verify| puppet-etcd-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-etcd-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-etcd-acceptance-single-node
    context: tarmak-puppet-module-etcd-acceptance-single-node
    always_run: false
    run_if_changed: "^(puppet/modules/etcd).*$"
    trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-etcd-acceptance-single-node|)( \\[.+\\])?$"
    rerun_command: "/test puppet-etcd-acceptance-single-node"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-etcd-acceptance-three-node
    context: tarmak-puppet-module-etcd-acceptance-three-node
    always_run: false
    run_if_changed: "^(puppet/modules/etcd).*$"
    trigger: "(?m)^/test( all| puppet| puppet-etcd| puppet-etcd-acceptance-three-node|)( \\[.+\\])?$"
    rerun_command: "/test puppet-etcd-acceptance-three-node"
  # puppet module fluent_bit
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-fluent_bit-quick-verify
    context: tarmak-puppet-module-fluent_bit-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/fluent_bit).*$"
    trigger: "(?m)^/test( all| puppet| puppet-fluent_bit| puppet-verify| puppet-fluent_bit-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-fluent_bit-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-fluent_bit-acceptance
    context: tarmak-puppet-module-fluent_bit-acceptance
    always_run: false
    run_if_changed: "^(puppet/modules/fluent_bit).*$"
    trigger: "(?m)^/test( all| puppet| puppet-fluent_bit| puppet-fluent_bit-acceptance|)( \\[.+\\])?$"
    rerun_command: "/test puppet-fluent_bit-acceptance"
  # puppet module kubernetes
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-kubernetes-quick-verify
    context: tarmak-puppet-module-kubernetes-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/kubernetes).*$"
    trigger: "(?m)^/test( all| puppet| puppet-kubernetes| puppet-verify| puppet-kubernetes-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-kubernetes-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-kubernetes-acceptance
    context: tarmak-puppet-module-kubernetes-acceptance
    always_run: false
    run_if_changed: "^(puppet/modules/kubernetes).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-kubernetes-acceptance|)( \\[.+\\])?$"
    rerun_command: "/test puppet-kubernetes-acceptance"
  # puppet module kubernetes_addons
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-kubernetes_addons-quick-verify
    context: tarmak-puppet-module-kubernetes_addons-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/kubernetes_addons).*$"
    trigger: "(?m)^/test( all| puppet| puppet-kubernetes_addons| puppet-verify| puppet-kubernetes_addons-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-kubernetes_addons-verify"
  # puppet module prometheus
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-prometheus-quick-verify
    context: tarmak-puppet-module-prometheus-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/prometheus).*$"
    trigger: "(?m)^/test( all| puppet| puppet-prometheus| puppet-verify| puppet-prometheus-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-prometheus-verify"
  # puppet module tarmak
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-tarmak-quick-verify
    context: tarmak-puppet-module-tarmak-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-verify| puppet-tarmak-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-11-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-11-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.11)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.11"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-11-ubuntu
    context: tarmak-puppet-module-tarmak-acceptance-1-11-ubuntu
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-ubuntu( v?1.11)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-ubuntu v1.11"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-14-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-14-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.14)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.14"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-13-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-13-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.13)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.13"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-12-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-12-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.12)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.12"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-10-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-10-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.10)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.10"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-9-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-9-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.9)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.9"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-tarmak-acceptance-1-8-centos
    context: tarmak-puppet-module-tarmak-acceptance-1-8-centos
    always_run: false
    run_if_changed: "^(puppet/modules).*$"
    trigger: "(?m)^/test( all| puppet| puppet-tarmak| puppet-tarmak-acceptance-centos( v?1.8)?|)( \\[.+\\])?$"
    rerun_command: "/test puppet-tarmak-acceptance-centos v1.8"
  # puppet module vault_client
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-vault_client-quick-verify
    context: tarmak-puppet-module-vault_client-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/vault_client).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_client| puppet-verify| puppet-vault_client-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_client-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-vault_client-acceptance-centos
    context: tarmak-puppet-module-vault_client-acceptance-centos
    always_run: false
    run_if_changed: "^(puppet/modules/vault_client).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_client| puppet-vault_client-acceptance-centos|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_client-acceptance-centos"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-vault_client-acceptance-ubuntu
    context: tarmak-puppet-module-vault_client-acceptance-ubuntu
    always_run: false
    run_if_changed: "^(puppet/modules/vault_client).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_client| puppet-vault_client-acceptance-ubuntu|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_client-acceptance-ubuntu"
  # puppet module vault_server
  - <<: *puppet_module_verify
    name: tarmak-puppet-module-vault_server-quick-verify
    context: tarmak-puppet-module-vault_server-quick-verify
    always_run: false
    run_if_changed: "^(puppet/modules/vault_server).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_server| puppet-verify| puppet-vault_server-verify|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_server-verify"
  - <<: *puppet_module_acceptance
    name: tarmak-puppet-module-vault_server-acceptance-centos
    context: tarmak-puppet-module-vault_server-acceptance-centos
    always_run: false
    run_if_changed: "^(puppet/modules/vault_server).*$"
    trigger: "(?m)^/test( all| puppet| puppet-vault_server| puppet-vault_server-acceptance-centos|)( \\[.+\\])?$"
    rerun_command: "/test puppet-vault_server-acceptance-centos"

  - name: tarmak-quick-verify
    always_run: true
    skip_report: false
    context: tarmak-quick-verify
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: golang:1.11.11
        command:
        - make
        - all
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify( quick)?|)( \\[.+\\])?$"
    rerun_command: "/test verify quick"

  - name: tarmak-docs-verify
    always_run: true
    skip_report: false
    context: tarmak-docs-verify
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/tarmak-sphinx-docs:v20180919-4a6536b
        securityContext:
          runAsUser: 0
        command:
        - make
        - -C
        - docs
        - ci
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify( docs)?|)( \\[.+\\])?$"
    rerun_command: "/test verify docs"
